defaults: &defaults
  docker:
    - image: circleci/node:lts
  working_directory: ~/repo

version: 2.1

orbs:
  node: circleci/node@5.0.0 

commands:
  build:
   steps:
    - node/install-packages:
          app-dir: "~/repo"
          cache-path: "~/repo/node_modules"
    - run: node --version
    - run:
        name: "Build"
        command: npm run build    

jobs:
 build-test:
   <<: *defaults
   working_directory: ~/repo
   steps:
    - checkout
    - build
    - run:
          name: "Run tests"
          command: npm run test

workflows:
  version: 2.1
  test_and_release:
   jobs:
    - build-test